name: dc_box_app
description: "A new Flutter project."

# 以下行可防止包被意外发布到pub.dev，使用 `flutter pub publish`。如果您想发布到 pub.dev，请删除此行
publish_to: 'none'

# 在 iOS 中，build-name 用作 CFBundleShortVersionString，而 build-number 用作 CFBundleVersion。
# 有关 iOS 版本控制的更多信息，请访问
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# 版本和构建器编号都可能在 flutter 中被覆盖,通过分别指定 --build-name 和 --build-number 进行构建。
# 在 Android 中，build-name 用作 versionName，build-number 用作 versionCode。
# 有关 Android 版本控制的更多信息，请访问 https://developer.android.com/studio/publish/versioning
version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

# Dependencies 指定您的包工作所需的其他包
# 运行 `flutter pub Upgrade --major-versions` 或 手动更改版本号 更新依赖项
# 可用版本，运行 `flutter pub outdated`
dependencies:
  flutter:
    sdk: flutter


  # 这是一个资源库，包含 Flutter 的 Cupertino 小部件使用的默认图标资源集。
  # https://pub.dev/packages/cupertino_icons
  cupertino_icons: ^1.0.6
  # MVVM框架  https://pub.dev/packages/get
  get: ^4.6.6
  # HTTP库  https://pub.dev/packages/dio
  dio: ^5.5.0+1
  # json转model类生成工具  https://pub.dev/packages/json_annotation
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
