name: dc_box_app
description: "A new Flutter project."

# 以下行可防止包被意外发布到pub.dev，使用 `flutter pub publish`。如果您想发布到 pub.dev，请删除此行
publish_to: 'none'

# 在 iOS 中，build-name 用作 CFBundleShortVersionString，而 build-number 用作 CFBundleVersion。
# 有关 iOS 版本控制的更多信息，请访问
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# 版本和构建器编号都可能在 flutter 中被覆盖,通过分别指定 --build-name 和 --build-number 进行构建。
# 在 Android 中，build-name 用作 versionName，build-number 用作 versionCode。
# 有关 Android 版本控制的更多信息，请访问 https://developer.android.com/studio/publish/versioning
version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

# Dependencies 指定您的包工作所需的其他包
# 运行 `flutter pub Upgrade --major-versions` 或 手动更改版本号 更新依赖项
# 可用版本，运行 `flutter pub outdated`
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  # 这是一个资源库，包含 Flutter 的 Cupertino 小部件使用的默认图标资源集。
  # https://pub.dev/packages/cupertino_icons
  cupertino_icons: ^1.0.6
  http: ^1.2.2
  # MVVM框架  https://pub.dev/packages/get
  get: ^5.0.0-release-candidate-9
  # 获取设备信息
  device_info_plus: ^10.1.1
  # 修改程序的桌面图标  https://pub-web.flutter-io.cn/packages/flutter_launcher_icons
  flutter_launcher_icons: ^0.13.1
  # 加解密  https://pub-web.flutter-io.cn/packages/encrypt
  encrypt: ^5.0.3
  # 设备id  https://pub.dev/packages/platform_device_id
  platform_device_id: ^1.0.1
  # 生成uuid  https://pub.dev/packages/uuid
  uuid: ^4.4.2
  # 包名资讯  https://pub.dev/packages/package_info_plus
  package_info_plus: ^8.0.2
  # 控制台信息打印组件  https://pub-web.flutter-io.cn/packages/logger
  logger: ^2.4.0
  # 提供跨平台（iOS、Android）API 来请求权限并检查其状态。您还可以打开设备的应用程序设置，以便用户授予权限。
  # https://pub-web.flutter-io.cn/packages/permission_handler
  permission_handler: ^11.3.1
  # Flutter初始化容器大小  https://pub.dev/packages/flutter_screenutil
  flutter_screenutil: ^5.9.0
  # HTTP库  https://pub.dev/packages/dio
  dio: ^5.5.0+1
  # json转model类生成工具  https://pub.dev/packages/json_annotation
  json_annotation: ^4.9.0
  # 状态管理工具  https://pub.dev/packages/get_storage
  get_storage: ^2.1.1
  # 安全性储存，数据会存储在手机的内存中  https://pub.dev/packages/flutter_secure_storage
  #  flutter_secure_storage: ^9.2.2
  # Flutter 的 Toast 库  https://pub.dev/packages/bot_toast
  bot_toast: ^4.1.3
  # 一个纯dart开发包，可以打印出完整的json格式数据并带有打印位置信息 https://pub.dev/packages/flutter_printer
  # flutter_printer: ^2.0.3
  # 路径管理，用于获取主机平台文件系统上的常用位置，例如临时目录和应用程序数据目录  https://pub.dev/packages/path_provider
  path_provider: ^2.1.4
  # 网络检测 https://pub.dev/packages/connectivity_plus
  connectivity_plus: ^6.0.5
  # webview  https://pub.dev/packages/flutter_inappwebview
  flutter_inappwebview: ^6.0.0
  basic_utils: ^5.7.0
  # 扫码  https://pub.dev/packages/mobile_scanner
  mobile_scanner: ^5.2.1
  # 生物辨識  https://pub.dev/packages/local_auth
  local_auth: ^2.3.0
  # swipe 组件  https://pub.dev/packages/carousel_slider
  carousel_slider: ^5.0.0
  # Dart 的加密算法  https://pub.dev/packages/crypto
  crypto: ^3.0.5
  # 验证码输入框  https://pub.dev/packages/crypto
  pin_code_fields: ^8.0.1
  # 倒计时组件  https://pub.dev/packages/flutter_countdown_timer
  flutter_countdown_timer: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # 此包包含一组推荐的 Flutter 应用程序、包和插件的 lint，以鼓励良好的编码实践。 analysis_options.yaml
  flutter_lints: ^3.0.0
  # json_annotation的构建工具  build_runner 包提供了使用 Dart 代码生成文件的具体方法。 文件始终直接在磁盘上生成，并且重建是增量式的
  build_runner: ^2.4.11
  # json_annotation的标记工具 当构建器找到用 package:json_annotation 中定义的类注释的成员时，它们会生成代码。
  json_serializable: ^6.8.0

# 有关此文件的通用 Dart 部分的信息，请参阅
# 以下页面：https://dart.dev/tools/pub/pubspec
# 以下部分专门针对 Flutter 包。
flutter:

  # 以下行确保 Material Icons 字体已包含在您的应用程序中，以便您可以在 Material Icons 类中使用图标。
  uses-material-design: true

  # 将assets添加到您的应用程序, like this:
  assets:
    - assets/icons/startup-1024x1024.png

  # 图像资源可以引用一个或多个特定于分辨率的 "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # 有关从包依赖项添加assets的详细信息, see
  # https://flutter.dev/assets-and-images/#from-packages

  # 请在此处添加字体部分
  # 此列表中的每个条目都应该有一个“family”键带有字体系列名称，“fonts”键带有列出字体的资源和其他描述符
  # For example:
  # fonts:
  #   - family: TestFont
  #     fonts:
  #       - asset: fonts/TestFont-Regular.ttf
  #       - asset: fonts/TestFont-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # 有关包依赖项中的字体的详细信息, see https://flutter.dev/custom-fonts/#from-packages
