// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'user_info_model.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

UserInfoModel _$UserInfoModelFromJson(Map<String, dynamic> json) =>
    UserInfoModel(
      loginName: json['loginName'] as String? ?? '',
      nickName: json['nickName'] as String? ?? '',
      countryCode: json['countryCode'] as String? ?? '',
      phone: json['phone'] as String? ?? '',
      email: json['email'] as String? ?? '',
      headUrl: json['headUrl'],
      userType: (json['userType'] as num?)?.toInt() ?? 0,
      kycStatus: json['kycStatus'],
      kycLevel: (json['kycLevel'] as num?)?.toInt() ?? 0,
      kycApplyStatus: json['kycApplyStatus'],
      authJunior: json['authJunior'],
      authJuniorKycApproveRemark: json['authJuniorKycApproveRemark'],
      juniorKycRemark: json['juniorKycRemark'],
      authHigher: json['authHigher'],
      authHigherKycApproveRemark: json['authHigherKycApproveRemark'],
      higherKycRemark: json['higherKycRemark'],
      securityLevel: (json['securityLevel'] as num?)?.toInt() ?? 0,
      totalOrderNum: json['totalOrderNum'],
      successOrderNum: json['successOrderNum'],
      hasTranPass: json['hasTranPass'] as bool? ?? false,
      pwdExpired: json['pwdExpired'] as bool? ?? false,
      transPwdExpired: json['transPwdExpired'] as bool? ?? false,
      tranPassFailTimes: (json['tranPassFailTimes'] as num?)?.toInt() ?? 0,
      boundOtp: json['boundOtp'] as bool? ?? false,
      boundBankCard: json['boundBankCard'] as bool? ?? false,
      verifyPhone: json['verifyPhone'] as bool? ?? false,
      verifyEmail: json['verifyEmail'] as bool? ?? false,
      verifyOtp: json['verifyOtp'] as bool? ?? false,
      addressWhitelist: json['addressWhitelist'] as bool? ?? false,
      doneWithdraw: json['doneWithdraw'] as bool? ?? false,
      biometrics: json['biometrics'] as bool? ?? false,
      screenshotProtection: json['screenshotProtection'] as bool? ?? false,
      replySms: json['replySms'] as bool? ?? false,
      antiPhishingCode: json['antiPhishingCode'],
      userFlag: (json['userFlag'] as num?)?.toInt() ?? 0,
      userFlagInvalidStart: json['userFlagInvalidStart'],
      userFlagInvalidEnd: json['userFlagInvalidEnd'],
      rechargeFlag: (json['rechargeFlag'] as num?)?.toInt() ?? 0,
      rechargeFlagInvalidStart: json['rechargeFlagInvalidStart'],
      rechargeFlagInvalidEnd: json['rechargeFlagInvalidEnd'],
      withdrawFlag: (json['withdrawFlag'] as num?)?.toInt() ?? 0,
      withdrawFlagInvalidStart: json['withdrawFlagInvalidStart'],
      withdrawFlagInvalidEnd: json['withdrawFlagInvalidEnd'],
      transferFlag: (json['transferFlag'] as num?)?.toInt() ?? 0,
      sellFlag: (json['sellFlag'] as num?)?.toInt() ?? 0,
      transferFlagInvalidStart: json['transferFlagInvalidStart'],
      transferFlagInvalidEnd: json['transferFlagInvalidEnd'],
      dcboxFirstLogin: json['dcboxFirstLogin'] as bool? ?? false,
      kycAllLimitSwitchOn: json['kycAllLimitSwitchOn'] as bool? ?? false,
      otcBuySwitchOn: json['otcBuySwitchOn'] as bool? ?? false,
      otcSwitchOn: json['otcSwitchOn'] as bool? ?? false,
      creditSwitchOn: json['creditSwitchOn'] as bool? ?? false,
      isTranPassAudit: json['isTranPassAudit'] as bool? ?? false,
      isKycBank: (json['isKycBank'] as num?)?.toInt() ?? 0,
      kycRealName: json['kycRealName'] as String? ?? '',
      idNo: json['idNo'] as String? ?? '',
      migrateFlag: json['migrateFlag'] as bool? ?? false,
      systemTime: (json['systemTime'] as num?)?.toInt() ?? 0,
      hasCreditCard: json['hasCreditCard'] as bool? ?? false,
      language: json['language'] as String? ?? '',
      isSpecialSupplier: json['isSpecialSupplier'],
      invitationCode: json['invitationCode'],
      whetherBindSuperior: json['whetherBindSuperior'] as bool? ?? false,
      whetherFirstLogin: json['whetherFirstLogin'] as bool? ?? false,
      kycBuyStatus: (json['kycBuyStatus'] as num?)?.toInt() ?? 0,
      token: json['token'] as String? ?? '',
    );

Map<String, dynamic> _$UserInfoModelToJson(UserInfoModel instance) =>
    <String, dynamic>{
      'loginName': instance.loginName,
      'nickName': instance.nickName,
      'countryCode': instance.countryCode,
      'phone': instance.phone,
      'email': instance.email,
      'headUrl': instance.headUrl,
      'userType': instance.userType,
      'kycStatus': instance.kycStatus,
      'kycLevel': instance.kycLevel,
      'kycApplyStatus': instance.kycApplyStatus,
      'authJunior': instance.authJunior,
      'authJuniorKycApproveRemark': instance.authJuniorKycApproveRemark,
      'juniorKycRemark': instance.juniorKycRemark,
      'authHigher': instance.authHigher,
      'authHigherKycApproveRemark': instance.authHigherKycApproveRemark,
      'higherKycRemark': instance.higherKycRemark,
      'securityLevel': instance.securityLevel,
      'totalOrderNum': instance.totalOrderNum,
      'successOrderNum': instance.successOrderNum,
      'hasTranPass': instance.hasTranPass,
      'pwdExpired': instance.pwdExpired,
      'transPwdExpired': instance.transPwdExpired,
      'tranPassFailTimes': instance.tranPassFailTimes,
      'boundOtp': instance.boundOtp,
      'boundBankCard': instance.boundBankCard,
      'verifyPhone': instance.verifyPhone,
      'verifyEmail': instance.verifyEmail,
      'verifyOtp': instance.verifyOtp,
      'addressWhitelist': instance.addressWhitelist,
      'doneWithdraw': instance.doneWithdraw,
      'biometrics': instance.biometrics,
      'screenshotProtection': instance.screenshotProtection,
      'replySms': instance.replySms,
      'antiPhishingCode': instance.antiPhishingCode,
      'userFlag': instance.userFlag,
      'userFlagInvalidStart': instance.userFlagInvalidStart,
      'userFlagInvalidEnd': instance.userFlagInvalidEnd,
      'rechargeFlag': instance.rechargeFlag,
      'rechargeFlagInvalidStart': instance.rechargeFlagInvalidStart,
      'rechargeFlagInvalidEnd': instance.rechargeFlagInvalidEnd,
      'withdrawFlag': instance.withdrawFlag,
      'withdrawFlagInvalidStart': instance.withdrawFlagInvalidStart,
      'withdrawFlagInvalidEnd': instance.withdrawFlagInvalidEnd,
      'transferFlag': instance.transferFlag,
      'sellFlag': instance.sellFlag,
      'transferFlagInvalidStart': instance.transferFlagInvalidStart,
      'transferFlagInvalidEnd': instance.transferFlagInvalidEnd,
      'dcboxFirstLogin': instance.dcboxFirstLogin,
      'kycAllLimitSwitchOn': instance.kycAllLimitSwitchOn,
      'otcBuySwitchOn': instance.otcBuySwitchOn,
      'otcSwitchOn': instance.otcSwitchOn,
      'creditSwitchOn': instance.creditSwitchOn,
      'isTranPassAudit': instance.isTranPassAudit,
      'isKycBank': instance.isKycBank,
      'kycRealName': instance.kycRealName,
      'idNo': instance.idNo,
      'migrateFlag': instance.migrateFlag,
      'systemTime': instance.systemTime,
      'hasCreditCard': instance.hasCreditCard,
      'language': instance.language,
      'isSpecialSupplier': instance.isSpecialSupplier,
      'invitationCode': instance.invitationCode,
      'whetherBindSuperior': instance.whetherBindSuperior,
      'whetherFirstLogin': instance.whetherFirstLogin,
      'kycBuyStatus': instance.kycBuyStatus,
      'token': instance.token,
    };
